### ISSUE TITLE
Verificar criação novo usuário

### ISSUE THREAD

**Issue by WesleyNL** [renatabrasil/pizzaria-sin5005#10]
Erro "Email translation missing: pt-BR.activerecord.errors.models.user.attributes.email.blank" mesmo com tudo preenchido corretamente.
Fluxo normal, menu acima de "Login".

**Comment by WesleyNL** [comment]
Possivelmente o problema está localizado no **modelo user.rb** na linha **devise** -> **:validatable**.
Tem alguns reports pela internet com isso (e se retirar ou colocar email = false, funciona, mas não é a melhor forma).

**Comment by renatabrasil** [comment]
Vou dar uma olhada nisso. Às vezes é só questão de configuração e é rápido. Acho que essa vai ser rápida.

**Comment by renatabrasil** [comment]
O buraco é mais embaixo hahaha.
Eu customizei o nosso devise adicionando o campo username e dizendo que é com ele que eu quero me autenticar. Por padrão, o devise usa o email para isso.

[http://jacopretorius.net/2014/03/adding-custom-fields-to-your-devise-user-model-in-rails-4.html](http://jacopretorius.net/2014/03/adding-custom-fields-to-your-devise-user-model-in-rails-4.html)

Basicamente eu preciso criar uma controller nova que herda a controller do Devise para adicionar o comportamento customizado que eu desejo.

**Comment by renatabrasil** [comment]
Quando eu tentei fazer o cadastro, o console me mostrou isso: 
`Unpermitted parameter: :email`
