### ISSUE TITLE
Verificar "Cadastrar pizza"

### ISSUE THREAD

**Issue by WesleyNL** [renatabrasil/pizzaria-sin5005#11]
undefined method `phone' ao carregar tela

**Comment by renatabrasil** [comment]
Eu comecei a desenvolver a história, mas não fui à frente.
O que eu posso dizer até agora é que a tabela no banco FOI criada, porém ainda não tem colunas. Olha como eu inseri as colunas que queria em cliente: db/migrate/20170906211117_add_columuns_to_empty_clients.rb

Esse arquivo tem o que eu fiz.

E esse link é a parte do bom guia do rails que fala sobre as migrations: [http://guides.rubyonrails.org/active_record_migrations.html](http://guides.rubyonrails.org/active_record_migrations.html)

Então falta:

1. Criar as colunas no banco (você mexe no banco através das migrations)
2. Fazer as actions da controller de pizza
3. Escrever os testes do cucumber e do RSPEC.

Vê como eu fiz para cliente. Olha minha issue #1 e vê onde mexi. Qualquer coisa: [http://guides.rubyonrails.org](http://guides.rubyonrails.org) explica como fazer.

**Comment by renatabrasil** [comment]
Passei essa tarefa pra você, tá?

**Comment by WesleyNL** [comment]
Okay, já estou fuçando. Pra quinta está fechado, então?

**Comment by renatabrasil** [comment]
Era bom pelo menos o cadastrar de cliente e de pizza. Ei... dá o pull que eu criei um super usuário.

Login: admin
senha: admin123

Ele já é criado no início do sistema.

**Comment by WesleyNL** [comment]
Dei mais cedo :D
