### ISSUE TITLE
Criar casos de testes no cucumber e RSpec para o CRUD Clientes

### ISSUE THREAD

**Issue by renatabrasil** [renatabrasil/pizzaria-sin5005#13]
Esta issue está associada à #2 

Está faltando mais casos de teste. A cobertura está em 98%

Falta testar quando não consegue cadastrar e vai para o fluxo alternativo. Eu pensava que tinha feito isso com RSpec, mas aparentemente falta algo.

Checar como resolver isso integrando os cenários do cucumber com os casos de teste do rspec.

**Comment by WesleyNL** [comment]
Coloquei como **+ _Priority_** por essa _issue_ estar mais avançada do que as outras do mesmo estilo, além de terminarmos 1 caso 100% para garantir apresentação e facilitar implementação nas outras.

**Comment by renatabrasil** [comment]
Os testes do **rspec** estão ok, mas o do **cucumber** foram suspensos. Agora devo corrigir isso.
