### ISSUE TITLE
Mapeamento de permissões

### ISSUE THREAD

**Issue by WesleyNL** [renatabrasil/pizzaria-sin5005#16]
Verificar e associar o que cada usuário - devidamente logado - poderá acessar/modificar.

**# Menu Funcionários**
1. Apenas o **admin** (dono) poderá **acessar** o menu.

**# Menu Pizzas**
1. Apenas o **admin** poderá **excluir** (desativar) dados.
2. Demais funcionalidades são liberadas para qualquer usuário registrado.

**# Menu Clientes**
1. Apenas o **admin** poderá **excluir** (desativar) dados.
2. Demais funcionalidades são liberadas para qualquer usuário registrado.

**# Menu Pedidos**
1. Apenas o **admin** poderá **emitir** **relatório de pedidos**.
2. Apenas o **admin** poderá **excluir** (desativar) dados.
3. Demais funcionalidades são liberadas para qualquer usuário registrado.

**# Observação de escopo**
1. **Clientes** não acessam o sistema.

Este mapeamento poderá ser alterado.

**Comment by renatabrasil** [comment]
Concordo.

A gente pode fazer isso usando a gema CanCan. No arquivo ability.rb a gente pode atribuir as permissões corretas para cada tipo de usuário.

**Comment by WesleyNL** [comment]
Estava dando uma olhada nisso 😄

**Comment by renatabrasil** [comment]
Viu a gema CanCan? é super fácil com ela. A gente pode colocar isso depois. Por ora vamos fazer mais uma história (além do cadastro para o cliente) e deixa essa das permissões para a segunda iteração de desenvolvimento. O que você acha?

**Comment by WesleyNL** [comment]
Sim, vi...
Sobre mais uma história, eu dei commit em várias coisas hoje o.o
Acho que o principal agora é o layout, hein...

**Comment by renatabrasil** [comment]
Mas a gente mostra só algumas funcionalidades. Porque se não ele vai querer ver coisa nova na próxima iteração, né?

**Comment by WesleyNL** [comment]
Sim, kk. Isso do acesso/autorização e os testes serão nas próximas, além de todo o fluxo de pedidos.
O layout e o cadastro de login que seriam interessantes agora.

**Comment by rafaeldesamascarenhas** [comment]
Xâ comigo!


=)

________________________________
De: Wesley Lombardi <notifications@github.com>
Enviado: segunda-feira, 2 de outubro de 2017 19:07:10
Para: renatabrasil/pizzaria-sin5005
Cc: Rafael de Sá Mascarenhas; Mention
Assunto: Re: [renatabrasil/pizzaria-sin5005] Mapeamento de permissões (#16)


Sim, kk. Isso do acesso/autorização e os testes serão nas próximas, além de todo o fluxo de pedidos.
O layout e o cadastro de login que seriam interessantes agora.

**Comment by WesleyNL** [comment]
Reorganização da descrição da tarefa para melhor visualização/compreensão e alterações no mapeamento.

**Comment by WesleyNL** [comment]
Mapeamento realizado. Será reaberto em caso de atualizações.
