### ISSUE TITLE
Fazer pedido

### ISSUE THREAD

**Issue by renatabrasil** [renatabrasil/pizzaria-sin5005#6]
## Cartão de história [5]

**Como:** usuário (cliente?)

**Quero:** fazer meu pedido

**Para:** pedir minha pizza com os itens cadastrados no sistema e o valor total do meu pedido.

___________________

## Descrição da tarefa:

1. Por questão de simplificação, os pedidos serão feitos a partir de um link no site: "Realizar pedido". Nesse link, o cliente pode ir escolhendo dentre as opções de pizza disponíveis (cadastradas no sistema) as desejadas. O valor de cada item é adicionado e um valor total é dado e o cliente tem a opção de "Finalizar pedido". Após finalizar o pedido, ele é redirecionado a uma página que exibe as informações da compra.

Tem que verificar com o cliente, mas já identifiquei a necessidade de guardar a data de realização do pedido (por causa da issue #7 ) e também de ter um atributo `status` com inicialmente duas opções (ATENDIDO, ABERTO) (também por causa da issue #7 ).

**Comment by renatabrasil** [comment]
**PRIORIDADE: 5**

**Comment by WesleyNL** [comment]
Ajustar para o funcionário registrar o pedido. Ajustar contexto.

**Comment by WesleyNL** [comment]
@renatabrasil, tudo bem com isso?
