### ISSUE TITLE
Atender pedido

### ISSUE THREAD

**Issue by renatabrasil** [renatabrasil/pizzaria-sin5005#7]
## Cartão de história [6]

**Como:** funcionário

**Quero:** aceitar o pedido do meu cliente

**Para:** dar início ao pedido do meu cliente.

___________________

## Descrição da tarefa:

Logado como funcionário, o usuário pode ver o link: "Atender pedidos".

Ao clicar no link "Atender pedidos", uma listagem com os pedidos com `status: ABERTO` deve aparecer com a opção "Atender". Essa opção muda o status para `status: ATENDIDO`.

**Comment by renatabrasil** [comment]
**PRIORIDADE: 6**

**Comment by WesleyNL** [comment]
Essa _issue_ será removida, já que o cliente não irá mais realizar pedidos online, certo?
